[package]
name = "rab"
version = "0.1.0"
authors = ["Reto Hablützel <rethab@protonmail.ch>"]
edition = "2018"

[dependencies]
mio = {version = "0.7", features = ["net", "os-poll"] }
structopt = "0.3"
url = "2"

